# Generated by Django 4.1 on 2023-06-02 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_num', models.PositiveIntegerField(db_column='ADMIN_NUM', primary_key=True, serialize=False)),
                ('admin_name', models.CharField(db_column='ADMIN_NAME', max_length=4)),
                ('admin_age', models.PositiveIntegerField(db_column='ADMIN_AGE')),
            ],
            options={
                'db_table': 'administrator',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_type', models.CharField(db_column='CLASS_TYPE', max_length=2, primary_key=True, serialize=False)),
                ('administrator_admin_num', models.ForeignKey(db_column='ADMINISTRATOR_ADMIN_NUM', on_delete=django.db.models.deletion.DO_NOTHING, to='HUFS.administrator')),
            ],
            options={
                'db_table': 'class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_num', models.PositiveIntegerField(db_column='ROOM_NUM', primary_key=True, serialize=False)),
                ('administrator_admin_num', models.ForeignKey(db_column='ADMINISTRATOR_ADMIN_NUM', on_delete=django.db.models.deletion.DO_NOTHING, to='HUFS.administrator')),
            ],
            options={
                'db_table': 'room',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_num', models.PositiveIntegerField(db_column='STU_NUM', primary_key=True, serialize=False)),
                ('stu_name', models.CharField(db_column='STU_NAME', max_length=4)),
                ('stu_age', models.PositiveIntegerField(db_column='STU_AGE')),
                ('stu_sex', models.CharField(db_column='STU_SEX', max_length=1)),
                ('stu_birth', models.DateField(db_column='STU_BIRTH')),
                ('stu_curriculum', models.CharField(db_column='STU_CURRICULUM', max_length=1)),
                ('stu_extraclass_1', models.CharField(db_column='STU_EXTRACLASS_1', max_length=2)),
                ('stu_extraclass_2', models.CharField(db_column='STU_EXTRACLASS_2', max_length=2)),
                ('stu_formerexam', models.DecimalField(db_column='STU_FORMEREXAM', decimal_places=2, max_digits=3)),
                ('stu_leave_date', models.DateField(db_column='STU_LEAVE_DATE')),
                ('stu_leave_reason', models.CharField(db_column='STU_LEAVE_REASON', max_length=100)),
                ('class_class_type', models.ForeignKey(db_column='CLASS_CLASS_TYPE', on_delete=django.db.models.deletion.DO_NOTHING, to='HUFS.class')),
                ('room_room_num', models.ForeignKey(db_column='ROOM_ROOM_NUM', on_delete=django.db.models.deletion.DO_NOTHING, to='HUFS.room')),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tea_num', models.PositiveIntegerField(db_column='TEA_NUM', primary_key=True, serialize=False)),
                ('tea_name', models.CharField(db_column='TEA_NAME', max_length=4)),
                ('tea_age', models.PositiveIntegerField(db_column='TEA_AGE')),
                ('tea_sex', models.CharField(db_column='TEA_SEX', max_length=1)),
                ('tea_subject', models.CharField(db_column='TEA_SUBJECT', max_length=2)),
            ],
            options={
                'db_table': 'teacher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_num', models.PositiveIntegerField(db_column='VISIT_NUM', primary_key=True, serialize=False)),
                ('visit_date', models.DateField(db_column='VISIT_DATE')),
                ('visit_visitor', models.CharField(db_column='VISIT_VISITOR', max_length=4)),
                ('visit_leavehour', models.PositiveIntegerField(db_column='VISIT_LEAVEHOUR')),
                ('administrator_admin_num', models.ForeignKey(db_column='ADMINISTRATOR_ADMIN_NUM', on_delete=django.db.models.deletion.DO_NOTHING, to='HUFS.administrator')),
                ('student_stu_num', models.ForeignKey(db_column='STUDENT_STU_NUM', on_delete=django.db.models.deletion.DO_NOTHING, to='HUFS.student')),
            ],
            options={
                'db_table': 'visit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('tita_num', models.PositiveIntegerField(db_column='TITA_NUM', primary_key=True, serialize=False)),
                ('tita_day', models.CharField(db_column='TITA_DAY', max_length=1)),
                ('tita_1c', models.CharField(db_column='TITA_1C', max_length=2)),
                ('tita_2c', models.CharField(db_column='TITA_2C', max_length=2)),
                ('tita_3c', models.CharField(db_column='TITA_3C', max_length=2)),
                ('tita_4c', models.CharField(db_column='TITA_4C', max_length=2)),
                ('class_class_type', models.ForeignKey(db_column='CLASS_CLASS_TYPE', on_delete=django.db.models.deletion.DO_NOTHING, to='HUFS.class')),
            ],
            options={
                'db_table': 'timetable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('mock_id', models.PositiveIntegerField(db_column='MOCK_ID', primary_key=True, serialize=False)),
                ('mock_kor', models.PositiveIntegerField(db_column='MOCK_KOR')),
                ('mock_math', models.PositiveIntegerField(db_column='MOCK_MATH')),
                ('mock_eng', models.PositiveIntegerField(db_column='MOCK_ENG')),
                ('mock_extraclass_1', models.PositiveIntegerField(db_column='MOCK_EXTRACLASS_1')),
                ('mock_extraclass_2', models.PositiveIntegerField(db_column='MOCK_EXTRACLASS_2')),
                ('date', models.TextField()),
                ('student_stu_num', models.ForeignKey(db_column='STUDENT_STU_NUM', on_delete=django.db.models.deletion.DO_NOTHING, to='HUFS.student')),
            ],
            options={
                'db_table': 'mock_test',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Counseling',
            fields=[
                ('cou_num', models.PositiveIntegerField(db_column='COU_NUM', primary_key=True, serialize=False)),
                ('cou_date', models.DateField(db_column='COU_DATE')),
                ('administrator_admin_num', models.ForeignKey(db_column='ADMINISTRATOR_ADMIN_NUM', on_delete=django.db.models.deletion.DO_NOTHING, to='HUFS.administrator')),
                ('student_stu_num', models.ForeignKey(db_column='STUDENT_STU_NUM', on_delete=django.db.models.deletion.DO_NOTHING, to='HUFS.student')),
            ],
            options={
                'db_table': 'counseling',
                'managed': True,
            },
        ),
    ]
