# Generated by Django 4.2.1 on 2023-06-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUFS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendclass',
            name='rec_class',
            field=models.CharField(db_column='rec_class', max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendclass',
            name='rec_classtype',
            field=models.CharField(db_column='rec_classtype', max_length=10),
        ),
    ]
